name: CI/CD
on: push
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Display some Text
        run: echo "Some Text"
      - name: Command in Multiline
        run: |
          node -v
